services:
  - type: web
    name: karaoke-lopeej
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: DJ_PIN
        sync: false
